
services:
  db:
    image: postgres:15-alpine # Use lightweight Postgres image, eg alpine variant if available
    container_name: course_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: course_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - course
    restart: unless-stopped

  backend:
    # image: course-backend
    build: 
      context: ./course-backend
      dockerfile: Dockerfile.backend
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://course_db:5432/course_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "9099:9099"
    depends_on:
      - db
    networks:
      - course
    restart: unless-stopped

  frontend:
    # image: course-frontend
    # Pass Dockerfile here if needed for custom build
    build: 
      context: ./course-frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - course
    restart: unless-stopped

volumes:
  db_data:

networks:
  course:
