services:
  db:
    image: postgres:15-alpine 
    container_name: course_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: course_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - course
    restart: unless-stopped
      

  redis:
    image: redis:7-alpine
    container_name: course_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data 
    networks:
      - course_redis
    restart: unless-stopped
  

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: ["start-dev"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - course
    restart: unless-stopped


  backend:
    build: 
      context: ./course-backend
      dockerfile: Dockerfile.backend
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://course_db:5432/course_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATA_REDIS_HOST: course_redis
      SPRING_DATA_REDIS_PORT: 6379
      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080
      KEYCLOAK_REALM: course-realm
      KEYCLOAK_RESOURCE: course-frontend

    ports:
      - "9099:9099"
    depends_on:
      - db
      - redis
      - keycloak
    networks:
      - course
      - course_redis
    restart: unless-stopped


  frontend:
    build: 
      context: ./course-frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "4800:80"
    depends_on:
      - backend
    networks:
      - course
    restart: unless-stopped

volumes:
  db_data:
  redis_data:
  keycloak_data:

networks:
  course:
    driver: bridge
  course_redis:
    driver: bridge
