
services:
  db:
    image: postgres:15
    container_name: course_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: course_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - course
    restart: unless-stopped

  backend:
    image: course-backend
    container_name: course_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://course_db:5432/course_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "9099:9099"
    depends_on:
      - db
    networks:
      - course
    restart: unless-stopped

  frontend:
    image: course-frontend
    container_name: course_frontend
    ports:
      - "7900:4800"
    depends_on:
      - backend
    networks:
      - course
    restart: unless-stopped

volumes:
  db_data:

networks:
  course:
