version: '3.9'

services:
  db:
    image: postgres:15-alpine 
    container_name: course_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: course_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - course
    restart: unless-stopped

  # redis:
  #   image: redis:7-alpine
  #   container_name: course_redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data 
  #   networks:
  #     - course
  #   restart: unless-stopped

  backend:
    build: 
      context: ./course-backend
      dockerfile: Dockerfile.backend
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://course_db:5432/course_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_REDIS_HOST: course_redis  
      SPRING_REDIS_PORT: 6379
    ports:
      - "9099:9099"
    depends_on:
      - db
      # - redis
    networks:
      - course
    restart: unless-stopped

  frontend:
    build: 
      context: ./course-frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - course
    restart: unless-stopped

volumes:
  db_data:
  redis_data:  

networks:
  course:
    driver: bridge